name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run Tests
      run: cmake --build build --target test
    - name: Install
      run: cmake --install build
    - name: Run Distcheck
      run: make distcheck -C build
